spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    url: jdbc:mysql://
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
