spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: snaptime
    url: jdbc:mysql://na2ru2.me:6306/snaptime
    password: snaptime1@
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect